### ISSUE TITLE
Missing resource values

### ISSUE THREAD

**Issue by oliveira-marcio** [udacity/nd940-cap-advanced-android-programming-project-starter#1]
It seems that a lot of resource values are missing in this starter code:

![image](https://user-images.githubusercontent.com/22889345/81809745-c16ba600-9519-11ea-8731-5d7073c11b1b.png)

**Comment by jdonlan** [comment]
This is intentional. Part of the process is to add this back and to ensure learners know how to utilize and implement Android resources properly using the res directory. I have added TODOs in each of those resource files to more clearly indicate the requirement.

**Comment by oliveira-marcio** [comment]
Sorry but I have to disagree with this approach. First of all, there's no TODO indicating that students are supposed to implement those missing resources references. If it's the case of forcing students to utilize resources properly, this should be a rubrics requirement and you could leave only a TODO indicating that and remove those broken links to these missing references.

Finally, the project description suggest that students leave UI to the end and focus in functionality first, but this is impossible since students will have to concern about UI first to fix those invalid references to be able to build the project.

![image](https://user-images.githubusercontent.com/22889345/81829261-9e99bb80-9532-11ea-9e42-0b4c5268f272.png)

And some of missing resources are text dimensions, label texts, view styles, etc.

**Comment by jdonlan** [comment]
I added the TODOs to both the resource values files and the layout files. I removed references to the resource values from the layout files so they would not prevent building the application until they were re-implemented at a later time per your suggestion.

**Comment by oliveira-marcio** [comment]
Awesome!
