### ISSUE TITLE
Screenshots are for the Mars application

### ISSUE THREAD

**Issue by eechien** [udacity/nd940-cap-advanced-android-programming-project-starter#3]
[Link to screenshots folder](https://github.com/udacity/nd940-cap-advanced-android-programming-project-starter/tree/master/starter/screenshots)

I expected them to be screenshots for this Political Preparedness project, so that I wouldn't have to repeatedly watch the [video walkthrough](https://www.youtube.com/watch?v=z1CV2N7JUig).

**Comment by SudKul** [comment]
Deleted them from the https://github.com/udacity/nd940-cap-advanced-android-programming-project-starter/tree/master/starter folder.
